#!/bin/sh
# embed_assets.sh OUT.c SYMBOL=FILE ...
#
# Writes a C source that embeds each FILE as
#   const unsigned char SYMBOL[] = { ... };
#   const unsigned long SYMBOL_size = <bytes>;
# Only POSIX sh, od, sed and wc, so it runs the same on Linux, macOS and MSYS2.
# The launcher art is embedded this way (see the Makefile and src/launcher_art.h);
# visualc/embed_assets.ps1 does the same for the Visual Studio build.
set -eu

out=$1
shift
tmp="$out.tmp"
mkdir -p "$(dirname "$out")"

{
	echo "/* Generated by tools/embed_assets.sh; do not edit. */"
	for pair in "$@"; do
		symbol=${pair%%=*}
		file=${pair#*=}
		size=$(wc -c < "$file" | tr -d ' ')
		echo "const unsigned char $symbol[] = {"
		od -An -v -tx1 "$file" | sed -e '/^ *$/d' -e 's/  */ /g' -e 's/^ //' -e 's/ *$//' -e 's/\([0-9a-f][0-9a-f]\)/0x\1/g' -e 's/ /,/g' -e 's/$/,/'
		echo "};"
		echo "const unsigned long ${symbol}_size = ${size}UL;"
	done
} > "$tmp"
mv "$tmp" "$out"
