#!/usr/bin/env python3
"""Generate src/resampler_table.h for the in-tree sample-rate converter.

The converter (src/resampler.c) upsamples the game's 8-bit mono 11025 Hz sound
effects to the mixer's output rate with a polyphase windowed-sinc filter.  SDL's
own converter uses the platform libm to build its filter, so its output differs
by an ulp between Apple's and glibc's libm; this table is generated once and
committed, and the runtime only does integer arithmetic, so every platform and
compiler produces identical samples.

Kernel design
-------------
    h(u) = A * sinc(A*u) * kaiser(u / HALF, BETA),   |u| <= HALF, 0 outside

where u is measured in input samples and A is the cutoff as a fraction of the
input sample rate times two (A = 2 * fc / Fin).  For the 11025 Hz sounds this
puts the -0.5 dB point at ~4980 Hz and the stopband (>= 5512.5 Hz, the input
Nyquist, where the first image starts) below -90 dB; the passband ripple below
4.5 kHz is < 0.01 dB.  That is flatter and far better suppressed than SDL's
resampler, whose own -0.5 dB point is ~4245 Hz and whose response is only
-6 dB at 5.5 kHz.

The table stores the kernel at HALF*SUBPHASES+1 points of 1/SUBPHASES input
samples, scaled by KERNEL_SCALE and rounded to integers.  The runtime linearly
interpolates between points; SUBPHASES=64 keeps the interpolation error below
the filter's own stopband (and is an exact multiple of the 4 phases of the
11025 -> 44100 case, so that path has no interpolation error at all).

Regenerate with:  python3 tools/gen_resampler_table.py
"""

import math
import os

# --- generator parameters ----------------------------------------------------
HALF = 48            # kernel half-length in input samples (96 taps total)
BETA = 9.0           # Kaiser window shape (A ~= 90 dB stopband)
A = 0.934            # cutoff: 2 * 5150/11025, i.e. 0.467 * the input rate
SUBPHASES = 64       # table points per input sample
SCALE = 1 << 20      # kernel fixed-point scale (Q20)


def bessel_i0(x):
    """Zeroth-order modified Bessel function of the first kind."""
    total = 1.0
    term = 1.0
    k = 1
    while True:
        term *= (x * x / 4.0) / (k * k)
        total += term
        if term < 1e-17 * total:
            return total
        k += 1


def kaiser(x, beta):
    if abs(x) > 1.0:
        return 0.0
    return bessel_i0(beta * math.sqrt(max(0.0, 1.0 - x * x))) / bessel_i0(beta)


def sinc(u):
    return 1.0 if u == 0.0 else math.sin(math.pi * u) / (math.pi * u)


def kernel(u):
    if abs(u) > HALF:
        return 0.0
    return A * sinc(A * u) * kaiser(u / HALF, BETA)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    path = os.path.join(root, "src", "resampler_table.h")
    n = HALF * SUBPHASES
    values = [int(round(kernel(k / SUBPHASES) * SCALE)) for k in range(n + 1)]

    with open(path, "w") as f:
        f.write("/* Generated by tools/gen_resampler_table.py -- do not edit.\n")
        f.write(" *\n")
        f.write(" * Polyphase interpolation kernel for src/resampler.c, sampled at\n")
        f.write(" * 1/%d input samples, h(u) = A*sinc(A*u)*kaiser(u/%d, %.1f)\n"
                % (SUBPHASES, HALF, BETA))
        f.write(" * with A = %.4f (cutoff %.0f Hz for the 11025 Hz sounds).\n"
                % (A, A / 2.0 * 11025.0))
        f.write(" * Scaled by %d (Q20); symmetric, so only u >= 0 is stored.\n */\n"
                % SCALE)
        f.write("\n#ifndef RESAMPLER_TABLE_H\n#define RESAMPLER_TABLE_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define RESAMPLER_KERNEL_HALF %d\n" % HALF)
        f.write("#define RESAMPLER_KERNEL_SUBPHASES %d\n" % SUBPHASES)
        f.write("#define RESAMPLER_KERNEL_SCALE (1 << 20)\n\n")
        f.write("static const int32_t resampler_kernel[%d] = {\n" % (n + 1))
        for i in range(0, n + 1, 8):
            f.write("\t" + ", ".join("%8d" % v for v in values[i:i + 8]) + ",\n")
        f.write("};\n\n#endif\n")

    print("wrote %s (%d coefficients, HALF=%d BETA=%.1f A=%.4f SUBPHASES=%d)"
          % (os.path.relpath(path, root), n + 1, HALF, BETA, A, SUBPHASES))


if __name__ == "__main__":
    main()
