# Embeds the same original launcher PNGs as tools/embed_assets.sh.
param([Parameter(Mandatory=$true)][string]$Output)
$ErrorActionPreference = "Stop"
$assets = [ordered]@{
    launcher_art_panel21 = "panel-tyrian21.png"
    launcher_art_panel2000 = "panel-tyrian2000.png"
    launcher_art_title21 = "title-tyrian21.png"
    launcher_art_title2000 = "title-tyrian2000.png"
}
$writer = [System.IO.StreamWriter]::new($Output, $false, [System.Text.Encoding]::ASCII)
try {
    $writer.WriteLine("/* Generated by visualc/embed_assets.ps1; do not edit. */")
    foreach ($symbol in $assets.Keys) {
        $bytes = [System.IO.File]::ReadAllBytes((Join-Path $PSScriptRoot ("..\assets\launcher\" + $assets[$symbol])))
        $writer.WriteLine("const unsigned char $symbol[] = {")
        for ($i = 0; $i -lt $bytes.Length; $i += 16) {
            $end = [Math]::Min($i + 15, $bytes.Length - 1)
            $line = ($bytes[$i..$end] | ForEach-Object { "0x{0:x2}" -f $_ }) -join ","
            $writer.WriteLine($line + ",")
        }
        $writer.WriteLine("};")
        $writer.WriteLine("const unsigned long " + $symbol + "_size = " + $bytes.Length + "UL;")
    }
} finally {
    $writer.Dispose()
}
